<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit56233965d5ec39f656019fc629c438e6
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'IU\\REDCapETL\\' => 13,
            'IU\\PHPCap\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'IU\\REDCapETL\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'IU\\PHPCap\\' => 
        array (
            0 => __DIR__ . '/..' . '/iu-redcap/phpcap/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit56233965d5ec39f656019fc629c438e6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit56233965d5ec39f656019fc629c438e6::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
