<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'IU\\REDCapETL\\' => array($baseDir . '/src'),
    'IU\\PHPCap\\' => array($vendorDir . '/iu-redcap/phpcap/src'),
);
