<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5cbd07f417cff6b2b54af498d270b465
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'IU\\REDCapETL\\' => 13,
            'IU\\PHPCap\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'IU\\REDCapETL\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'IU\\PHPCap\\' => 
        array (
            0 => __DIR__ . '/..' . '/iu-redcap/phpcap/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5cbd07f417cff6b2b54af498d270b465::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5cbd07f417cff6b2b54af498d270b465::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5cbd07f417cff6b2b54af498d270b465::$classMap;

        }, null, ClassLoader::class);
    }
}
